version: '3.3'

networks:
  celestia:
    ipam:
      driver: default
      config:
        - subnet: 172.27.10.0/24

services:
  validator2:
    container_name: validator
    image: sysrex/validator:v0.11.0
    ports:
      - "1317:1317"
      - "9090:9090"
      - "26656:26656"
      - "26657:26657"
    command: [
      "start",
      "--moniker", "celestia-app-full-1",
      "--rpc.laddr", "tcp://0.0.0.0:26657"
    ]
    volumes:
      - /opt/validator2/config:/opt/config:rw
      - /opt/validator2/data/app:/opt/data:rw
    networks:
      celestia:
        ipv4_address: 172.27.10.9
  bridge:
    container_name: bridge
    image: sysrex/boostrapper:latest
    restart: always
    ports:
      - "2121:2121"
      - "6000:6000"
      - "26658:26658"
    environment:
      - NODE_TYPE=bridge
      - CELESTIA_CUSTOM=mocha:8038B21032C941372ED601699857043C12E5CC7D5945DCEEA4567D11B5712526
    command: [
            "celestia", "bridge",
            "--node.store", "/root/.celestia-bridge",
            "start",
            "--core.ip",
            "172.27.10.9",
            "--core.rpc.port",
            "26657"
             ]
    volumes:
       - /opt/validator2/data/bridge:/root:rw
    depends_on:
      - validator2
    networks:
      celestia:
        ipv4_address: 172.27.10.10