version: "3.3"

networks:
  celestia:
    ipam:
      driver: default
      config:
        - subnet: 172.27.10.0/24

services:
  full:
      container_name: full
      image: sysrex/celestia-node:v0.6.1
      restart: always
      ports:
        - "2121:2121"
        - "6000:6000"
        - "26658:26658"
      environment:
        - NODE_TYPE=full
      command: [
              "celestia", "full",
              "--node.store", "/root/.celestia-full",
              "start",
              "--headers.trusted-hash",
              "04EE55B212745B88F29943D7B9528C415473A211F12EEF6E9333EF32E4DEAF3C",
              "--headers.trusted-peers",
              "/ip4/34.77.147.236/tcp/2121/p2p/12D3KooWNpRWxpi1APzV6CnwHvdgNRuTUbMNvg4ta2i1fnqYXR7H"
               ]
      volumes:
        - /opt/validator2/data/full:/root:rw
      networks:
        celestia:
          ipv4_address: 172.27.10.11